# Generated by Django 5.2.1 on 2025-05-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
