name: Code style check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8:
    name: Run flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r backend/requirements.txt

      - name: Run flake8
        run: |
          flake8 backend --exclude=__init__.py,migrations --max-line-length=119
